- name: copping the {{COMPONENT}} repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: "{{COMPONENT}}-org"
    state: present

- name: starting {{COMPONENT}}
  systemd:
    name: 
    state: restarted
    enabled: yes
    daemon_reload: yes