---
- name: Demo on vars
  hosts: all
  #gather_facts: no #if you dont want facts then use it
  tasks:
    - name: printing the default variable
      ansible.builtin.debug:
        msg: "The server flavor is '{{ ansible_distribution }}'"
    - name: printing the MAC address of the sesrver 
      ansible.builtin.debug:
        msg: "The MAC address of the server is  '{{ ansible_default_ipv4.macaddress  }}'"  