---
- name: Demo on vars
  hosts: all
  tasks:
    - name: printing the default variable
      ansible.builtin.debug:
        msg: "The server flavor is '{{ ansible_distribution }}'"










# - name: Demo on vars
#   hosts: all
#   tasks:
#     name: printing the defauly variable
#     ansible.builtin.debug:
#       msg: ""The server flafour is '{{ansible_distribution}}'"

  