- name: shell commanda
  hosts: all
  #gather_facts: no #if you dont want facts then use it
  tasks:
    - name: Running up time command
      ansible.builtin.shell: uptime
      register: out

    - name: Printing up time command output
      ansible.builtin.debug:
        msg: "The OutPut OF The UP_TIME Command IS : {{out.stdout}}" 
