---
- name: Demo on Conditions 
  hosts: all
  tasks:
    - name: Run this when only ansible distribution is centos
      when: ansible_distribution == "centOs"
      ansible.builtin.debug:
        msg: "welcome to centOs"
    - name: Run this when only ansible distribution is centos
      when: ansible_distribution == "ubantu"
      ansible.builtin.debug:
        msg: "welcome to centOs"

