- name: Demo on loops
  hosts: all
  tasks: 
    - name: Demo on using loops
      loop:
        - 100
        - 200
        - 300
      ansible.builtin.debug:
        msg: "value is {{item}}" # item is a key word to represents value in the loop