
- name: Configuring Node.js Repository
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Installing Node.js
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Creating App User
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and Extracting the {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract

- name: Performing {{COMPONENT}} Clean-up
  ansible.builtin.file:
    path: /home/{{ AppUser }}/{{ COMPONENT }}
    state: absent
  ignore_errors: yes  # Ignoring errors for clean-up

- name: copying the file to {{AppUser}} home directore 
  ansible.builtin.copy: 
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{AppUser}}/{{COMPONENT}}/
    owner: "{{AppUser}}"
    group: "{{AppUser}}"
    remote_src: yes

- name: Installing Artifacts with npm install
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}/

- name: starting the {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: conf_ser

- name: setting the Host server Name
  ansible.builtin.include_role:
    name: common
    tasks_from: host_name_setup

